setono_sylius_gift_card_shop:
    resource: "@SetonoSyliusGiftCardPlugin/Resources/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

setono_sylius_gift_card_admin:
    resource: "@SetonoSyliusGiftCardPlugin/Resources/config/routes/admin.yaml"
    prefix: /admin

setono_sylius_gift_card_admin_ajax:
    resource: "@SetonoSyliusGiftCardPlugin/Resources/config/routes/admin_ajax.yaml"
    prefix: /admin/ajax

setono_sylius_gift_card_admin_partial:
    resource: "@SetonoSyliusGiftCardPlugin/Resources/config/routes/admin_partial.yaml"
    prefix: /admin/partial
    
setono_sylius_gift_card_admin_api:
    resource: "@SetonoSyliusGiftCardPlugin/Resources/config/routes/admin_api.yaml"
    prefix: /api/v{version}
